---
- name: Installing kb articles 
  hosts: winserver
  tasks:
     - name: Download KB3172729 for Server 2012 R2
       win_get_url:
        url: http://download.windowsupdate.com/d/msdownload/update/software/secu/2016/07/windows8.1-kb3172729-x64_e8003822a7ef4705cbb65623b72fd3cec73fe222.msu
        dest: C:\temp\windows8.1-kb3172729-x64_e8003822a7ef4705cbb65623b72fd3cec73fe222.msu
     - name: Install all security updates with automatic reboots
       tags: sec1 
       win_updates:
         category_names:
         - SecurityUpdates
         whitelist: 
            - KB3172729
            - KB4477136
         state: searched 
       register: patchoutput
       tags: sec1 
     - debug: var=patchoutput 
       tags: sec1 
     - name: install hotfix validating KB
       win_hotfix:
        hotfix_kb: KB3172729
        source: C:\temp\windows8.1-kb3172729-x64_e8003822a7ef4705cbb65623b72fd3cec73fe222.msu
        state: present 
       register: hotfixstatus
     - debug: var=hotfixstatus.changed 
     - debug: var=hotfixstatus.kb 
