---
##Demo Ansible Playbook to stop Application Services
- name: Running service stop script
  hosts: linuxserver
  become: yes
  vars:
    scriptFile: /tmp/test.sh
  tasks:
  - name: stop the app service
    shell: "sh {{ scriptFile }} > /tmp/test.log"
...

