---
##Demo Ansible Playbook to stop Application Services
- name: Running service stop script 
  hosts: linuxserver
  become: yes
  vars:
    scriptFile: /tmp/test.sh
  tasks:
  - name: stop the app service
    shell: "sh -x {{ scriptFile }} > /tmp/test.log"
    register: helloworld
  - debug: var=helloworld
...
