---
- name: Windows_updates
  hosts: winserver
  tasks:
    - name: Install all critical and security updates
      win_updates:
        category_names:
        - CriticalUpdates
        - SecurityUpdates
        - UpdateRollups
        state: installed
      register: update_result
...
