---
- name: Windows_updates
  hosts: winserver 
  tasks:
     #check if there any missing updates
       - block:
          - name: Check for missing updates.
            win_updates: state=searched
            register: update_count
          - name: List missing updates
            debug: var=update_count
...

